/* Components */
import { Metadata } from 'next';
import { Providers } from '@/lib/providers';

/* Instruments */
import './styles/globals.scss';

import Nav from './components/Nav';
import Header from './components/Header';
import AuthGuard from './AuthGuard';

export const metadata: Metadata = {
    title: 'Dooiu Dynamic Pricing',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body>
                <Providers>
                    <Header />
                    <AuthGuard>{children}</AuthGuard>
                    <Nav />
                </Providers>
            </body>
        </html>
    );
}
